### ISSUE TITLE
Highlight the line the cursor is on

### ISSUE THREAD

**Issue by snim2** [softdevteam/eco#138]
It would be useful to have the current line highlighted, but for debugging, this can be used to track which line the debugger is currently executing (we can do this just by moving the cursor).

Making this work with Eco themes might need some thought.

**Comment by ptersilie** [comment]
If no one objects I can take on this issue as I am currently pushing some other aesthetic changes.

**Comment by snim2** [comment]
Fine by me, if @djmcalleja doesn't mind

**Comment by djmcalleja** [comment]
Sure, go ahead

**Comment by ptersilie** [comment]
Okay, I added the possibility to highlight the current line in PR #143. @djmcalleja only needs to change the debugger to move the cursor to the currently executed line either in #141 once we merged #143 or the other way around (depending on what is merged first).

**Comment by snim2** [comment]
Closing, fixed in #143
