### ISSUE TITLE
Pop up a dialog box if the user tries to execute a syntactically incorrect program

### ISSUE THREAD

**Issue by vext01** [softdevteam/eco#151]
Minor quibble. Just because it's not always obvious why a program has no output when executed.

**Comment by ltratt** [comment]
+1

I sometimes get a bit confused by this, until I remember to look at the terminal.

I think this would be a good one for @djmcalleja to have a quick look at.

**Comment by djmcalleja** [comment]
Sure, I can do that.

**Comment by ptersilie** [comment]
:+1: Something like `Failed to export program. Please check if your program is syntactically correct before exporting`.

**Comment by vext01** [comment]
Why "please check", eco should know if it's correct or not, no?

**Comment by ptersilie** [comment]
maybe "please check that ... is valid before exporting"

**Comment by ptersilie** [comment]
I dunno. Was just a suggestion. Could also say "Sorry dude. Can't export cus invalid."

**Comment by vext01** [comment]
How about:

```
Eco cannot execute this program because it is syntactically incorrect
```

Replace "execute" with "export" as context requires.

**Comment by vext01** [comment]
(But I do like your slang error message too)

**Comment by ltratt** [comment]
I prefer "syntactically invalid", but I think Edd's message is otherwise about right.

**Comment by ptersilie** [comment]
Okay let's go with `Eco cannot execute/export this program because it is syntactically invalid`.

**Comment by djmcalleja** [comment]
I'm supposed to make a pull request for this, right? Who should I assign it to?

**Comment by snim2** [comment]
For issues, usually the person who raised the original issue (so, @vext01 )

**Comment by djmcalleja** [comment]
Right, ok
