### ISSUE TITLE
Parsing not triggering?

### ISSUE THREAD

**Issue by ltratt** [softdevteam/eco#154]
1) Load in `basiccalc.eco`
2) Add the following text on a new line after `%implicit_ws=true`: `%left "` (i.e. don't close the `"`). Note that the parsing status is green when I think it should be red.
3) Select the whole file, cut it (Ctrl-X), then paste it back in. The parsing status is now red.

**Comment by ptersilie** [comment]
Works for me. Do I need to paste that line or type it in manually? I typed it in and it worked as expected.

**Comment by ptersilie** [comment]
Nevermind. I typed in the wrong line. I can reproduce it now

**Comment by ptersilie** [comment]
Ah it's not a bug in Eco. It's a bug in the EcoGrammar grammar, which for some reason lexes a single quote as a terminal.
