### ISSUE TITLE
Feature request: context menu option to clear console

### ISSUE THREAD

**Issue by snim2** [softdevteam/eco#21]

**Comment by ptersilie** [comment]
Doesn't the console clear automatically each time you run a program?

**Comment by snim2** [comment]
It does, but sometimes you might want to clear it manually.

**Comment by ptersilie** [comment]
Fair enough. I'll put it on my todo list. :)

**Comment by ltratt** [comment]
I agree, this would be useful. I sometimes write a blank program and run it to clear the console.
