### ISSUE TITLE
Image paths in HTML + Python + SQL file cannot contain dashes `-`

### ISSUE THREAD

**Issue by ComFreek** [softdevteam/eco#272]
I really wondered why Eco wouldn't accept my image path until I realized the syntax doesn't account for dashes in filenames:
![image](https://user-images.githubusercontent.com/1827709/72203284-c7695180-3469-11ea-8fcc-299cd0d7223c.png)

**Comment by ltratt** [comment]
We should probably think more carefully about the valid characters in a leaf name so that we don't keep forcing users to bump into this same problem. Until we do that https://github.com/softdevteam/eco/pull/273 should fix the immediate problem.

**Comment by ComFreek** [comment]
Thank you! If I understand Eco's principles correctly, then there shouldn't be syntax ambiguity anyway due to the existence of the image language box. Hence, is there any reason why you don't allow all characters?

In fact, that way even filenames containing LF newlines -- which are valid on Linux systems -- could be supported.

**Comment by ltratt** [comment]
Possibly we should!

**Comment by ptersilie** [comment]
I guess if we were to only allow supported characters then we would have to supply different lexing rules depending on the operating system (e.g. Linux allows `:` in filenames, Windows doesn't). So I agree that allowing all characters may be the easiest solution for now.
