### ISSUE TITLE
Implement support for extended PyHyp backtrace information.

### ISSUE THREAD

**Issue by vext01** [softdevteam/eco#57]
The compilation functions used in PyHyp now accept additional arguments which allow the editor to feedback information which can later be used in the VM for backtraces. Although the VM could figure this stuff out itself at runtime, it is more convenient for the editor to supply this info as it already knows this ahead of time.

For the functions:
- `compile_py_func_global` 
- `compile_py_func`
- `compile_py_meth`
- `compile_php_func`

eco should pass two additional arguments:
- `filename` -- the filename in which the language box appears.
- `line_offset` -- the line number in `filename` in which the language box appears.

This is required for the PyHyp paper.

Many thanks

**Comment by ptersilie** [comment]
A few questions:
- Is this the syntax for the function calls: `compile_py_meth(class, content, filename, line_offset)`?
- What is filename supposed to be? The full path to the eco file we are exporting?

**Comment by vext01** [comment]
Here's the definition of `compile_py_meth`: https://github.com/hippyvm/hippyvm/blob/pypy_bridge/hippy/module/pypy_bridge/bridge.py#L164

You can safely ignore the `interp` argument as that is RPython magic. Look in the same file for the other compilation functions.

Filename is what the user thinks he is editing, so I guess the eco filename(?) let's try it.

**Comment by ptersilie** [comment]
Do we really need the filename in each `compile_*`? Because it's the same for all of them.

**Comment by vext01** [comment]
I'm not sure what would happen if you only provided a line number actually. For now, let's always provide the filename, and I will add a note in the post-submission TODO to look into this. Seems reasonable?

**Comment by ltratt** [comment]
This dates back from an early idea where we would possibly compile fragments ahead of time into bytecode (i.e. they'd need to know which file they actually came from). For the time being, it is pointless, but support for it doesn't really cost us anything.

**Comment by ptersilie** [comment]
Well, it costs me touching a lot of code to forward the filename to all the different spots from where code can be exported and then forwarding that filename again to all the export walkers that are used for the different language types. But if that is what you guys want. Someone just needs to test this properly that it works in all cases as I currently don't have PyHyp to test.

**Comment by vext01** [comment]
I've not heard of the ahead of time compilation thing before.

Off the top of my head, the reason I used a filename is because the bytecode caches are per-filename. This is because the same code in different files can have a different meaning in the wake of different lexical scopes. Each filename/lineno pair uniquely identifies the lexical scope of a function.

**Comment by ptersilie** [comment]
Ah another question: What do I supply if there is no filename? `None`?

**Comment by ltratt** [comment]
Why not just use `__file__` in the exporter for the time being for the filename? That'll impose the fewest changes on Eco and PyHyp.

**Comment by vext01** [comment]
There is always a filename, no? Do you mean because the user hasn't saved yet?

**Comment by ptersilie** [comment]
@ltratt Because that wouldn't be correct. If I understood this correctly, we want the eco-file and the line numbers as they are in Eco. So that when we get an error, so the user can see which line failed.

@vext01 Yes, you can run programs without saving them (which includes exporting them).

**Comment by ltratt** [comment]
Ah, yes, good point.

**Comment by ptersilie** [comment]
I got the line numbers already. Was a bit tricky as each languagebox needs to count their lines and add them to the total amount of lines.

I just have to do the filename now.

**Comment by vext01** [comment]
In the case of an unsave program, I guess you could do something like MS word does, e.g. each tab is "untitled1.eco", "untitled2.eco"...

If you want quick hack, just always pass `__file__` as laurie says. Not sure what the PHP equivalent would be though. Google time.

**Comment by vext01** [comment]
Actually I'm not even sure what `__file__` reports in a Python box...

**Comment by ptersilie** [comment]
Looks like Python says `<stdin>`:

```
>>> x = 1 + {
... 
... s
... ;
  File "<stdin>", line 4
    ;
    ^
SyntaxError: invalid syntax
>>> 
```

**Comment by vext01** [comment]
Interesting...

**Comment by ptersilie** [comment]
I will give it just `None` for now and when you throw your error in the VM you can choose whatever you feel like. :)

**Comment by vext01** [comment]
OK. If it's really hard to do in Eco, I can live with that.

**Comment by ptersilie** [comment]
It's not about being hard. It's about what you want if someone runs a program without saving it. I chose `None` for now.

**Comment by ptersilie** [comment]
Okay, so this program
![newexport](https://cloud.githubusercontent.com/assets/375552/11506361/0808b4f6-9847-11e5-84d4-e0fbc125ada4.png)

gives me this export:

```
<?php{
class X {

    function test(){
        print(12);
    }






}
compile_py_meth("X", "def x():\n        print \"test\"", "/home/lukas/temp/pyhyp.eco", 7);
compile_py_meth("X", "def another():\n\n        compile_php_func(\"\"\"\nfunction test2(){\n            return 12;\n        }\n\"\"\", \"/home/lukas/temp/pyhyp.eco\", 12)\n        print \"another\"", "/home/lukas/temp/pyhyp.eco", 10);
compile_py_meth("X", "def another2():\n        pass", "/home/lukas/temp/pyhyp.eco", 17);

compile_py_func_global("def globalone():\n    pass", "/home/lukas/temp/pyhyp.eco", 21);

$s = compile_py_func("def bla():\n    pass", "/home/lukas/temp/pyhyp.eco", 24);;
}?>
```

Does that look sensible?

**Comment by vext01** [comment]
Ah i see. Yes that looks good.

Please wait for me to test the branch though. I may not get onto that today.

**Comment by ptersilie** [comment]
Haven't commited and pushed yet. Will do later.
