### ISSUE TITLE
Pressing Ctrl-L outside of a file causes a crash

### ISSUE THREAD

**Issue by ltratt** [softdevteam/eco#59]
Load Eco and press Ctrl-L immediately (don't create a file first!):

```
Traceback (most recent call last):
  File "eco.py", line 814, in show_lbox_menu
    self.getEditor().showLanguageBoxMenu()
AttributeError: 'NoneType' object has no attribute 'showLanguageBoxMenu'
```

**Comment by ptersilie** [comment]
Don't always do things you are not supposed to. ;)

(It's an easy fix though. I'll do it later).

**Comment by ltratt** [comment]
I didn't mean to... it just happened!

**Comment by ptersilie** [comment]
Actually this is true for a lot of commands, e.g. copy, past, undo, redo. I'll fix this properly and deactivate all invalid menu options if no file is loaded.
