### ISSUE TITLE
Show Stategraph raises Python exception

### ISSUE THREAD

**Issue by snim2** [softdevteam/eco#8]
This issue report is based on the code given in `TUTORIAL`, which Eco shows to be correctly parsed.

Steps to reproduce:
1. Reproduce the code from `TUTORIAL`
2. Click on **View** in the menu
3. Select **StateGraph** from the drop-down
4. Click on **Show whole graph**

Traceback is:

``` python
$ Traceback (most recent call last):
  File "eco.py", line 265, in showWholeGraph
    self.viewer.create_pydot_graph(editor.tm.get_mainparser().graph)
  File "/home/snim2/Desktop/working/snim2/eco/lib/eco/viewer.py", line 170, in create_pydot_graph
    if isinstance(node, AstNode):
AttributeError: 'NoneType' object has no attribute 'state_sets'
```

**Comment by ptersilie** [comment]
Ah, the reason for this is that we cache the syntax table. So the next time you create a new language X, it only loads the syntaxtable from the cache, not the stategraph. The correct solution to this is that when using the cached version we should disable the stategraph menu.
