### ISSUE TITLE
Line numbers greater than 9

### ISSUE THREAD

**Issue by snim2** [softdevteam/eco#9]
This is not a major bug and probably a WONTFIX for version 1, but I thought it was worth documenting.

When I run through the tutorial I get line numbers that run from `1--9` and then line `0` below that. When I add another newline the gutter that contains the line numbers expands a little and I can see `10` where there used to be a `0` and `11` renders correctly.

**Comment by ptersilie** [comment]
That actually sounds like an easy fix. I probably just have to change some fixed number 9 to 10. Eco used to start with line 0 until it was pointed out to me that it should start with 1. That's probably why I hard coded in to expand linenumbers after line 10 instead of 9.

**Comment by snim2** [comment]
Ah, cool!
