### ISSUE TITLE
No evaluation of tree after cutting or pasting code

### ISSUE THREAD

**Issue by jaheba** [softdevteam/eco#95]
When pasting code the evaluation of the tree is not updated. The same happens when new code is pasted into eco.

**Comment by ptersilie** [comment]
Yes this is a small bug. You have to edit something to trigger reparsing. There's probably just a function call to `reparse()` missing somewhere.

**Comment by ltratt** [comment]
Does `reparse` check the whole tree? Can you tell it which point definitely changed?

**Comment by ptersilie** [comment]
Nah `reparse()` only repairs by default. You have to add some argument to make a full reparse.

**Comment by ltratt** [comment]
OK, so that should work fine then. Ignore me!
