### ISSUE TITLE
Missing JavaScript grammar features

### ISSUE THREAD

**Issue by jaheba** [softdevteam/eco#98]
- [ ] Division: `1/2`
- [ ] "#hello"
- [ ] `1.2`;
- [ ] `var _ = 3`;
- [ ] `var $ = 4`;
- [ ] `var $_$ = 5`;
- [ ] `var x = 6 > 7`;

**Comment by jaheba** [comment]
The `#` in strings seems to be fixable by adding a rule like `NONSPACE = "\S"`.

**Comment by ptersilie** [comment]
Ah, yes. In the other grammars we defined a matchall token that catches everything that is not defined by some other lexing rule. This is needed to allow arbitrary text within Strings and comments.
